import Head from "next/head";
import styles from "../styles/Home.module.scss";
import ProgramList from "@/components/ProgramList/ProgramList";
import { GetServerSideProps } from "next";
import { HomeProps, Program } from "@/types/types";
import axios from "axios";
import FooterBlock from "@/components/FooterBlock/FooterBlock";

const Home = ({ programs }: HomeProps) => {
  return (
    <>
      <Head>
        <title>MBA courses App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.container}`}>
        <h2 className={`${styles.headerTitle}`}>
          Специализированные дисциплины
        </h2>
        <ProgramList programs={programs}></ProgramList>
        <FooterBlock />
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  try {
    const response = await axios.get<Program[]>(
      "https://api.moscow.mba/products",
      {
        params: {
          _limit: 5,
        },
      },
    );
    const programs = response.data;
    return { props: { programs } };
  } catch (error) {
    console.error("Error fetching programs:", error);
    return { props: { programs: [] } };
  }
};

export default Home;
